services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - library-network

  library:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: library
      DB_PORT: 5432
    ports:
      - "8080:8080"
    networks:
      - library-network
    command: ["go", "run", "main.go"]

networks:
  library-network:
    driver: bridge
